[workspace]
members = ["que", "examples/*"]
resolver = "2"

[workspace.dependencies]
bytemuck = { version = "1.16.3" }
nix = { version = "0.29", features = [
    "event",
    "poll",
    "mman",
    "fs",
    "feature",
] }
que = { path = "que" }
