use std::sync::atomic::Ordering;
use std::{ptr::NonNull, sync::Arc};

use bytemuck::AnyBitPattern;

use crate::{
    error::QueError, headless_spmc::MAGIC, page_size::PageSize,
    shmem::Shmem, ChannelMode, ShmemMode,
};

use super::{burst_amount, Channel};

unsafe impl<M: ChannelMode<T>, T, const N: usize> Send
    for Consumer<M, T, N>
{
}

#[repr(C)]
pub struct Consumer<M: ChannelMode<T>, T, const N: usize> {
    spsc: NonNull<Channel<M, T, N>>,
    head: usize,
    interval: usize,
    consumer_index: usize,
    last_producer_heartbeat: usize,
}

impl<T: AnyBitPattern, const N: usize> Consumer<ShmemMode, T, N> {
    /// Joins an existing channel back by shared memory as a consumer.
    pub unsafe fn join_shmem(
        shmem_id: &str,
        #[cfg(target_os = "linux")] page_size: PageSize,
    ) -> Result<Consumer<ShmemMode, T, N>, QueError> {
        Self::join_shmem_multi(
            shmem_id,
            #[cfg(target_os = "linux")]
            page_size,
            0,
            1,
        )
    }

    /// Joins an existing channel back by shared memory as a consumer.
    ///
    /// `interval` is the number of consumers. This channel is not FIFO!
    /// To consume all produced values, you must consume all values
    /// generated by all consumers generated via `next_multi`.
    pub unsafe fn join_shmem_multi(
        shmem_id: &str,
        #[cfg(target_os = "linux")] page_size: PageSize,
        index: usize,
        num_consumers: usize,
    ) -> Result<Consumer<ShmemMode, T, N>, QueError> {
        #[cfg(not(target_os = "linux"))]
        let page_size = PageSize::Standard;

        // Calculate buffer size.
        // If using huge pages, we must uplign to page size.
        let buffer_size: i64 = page_size
            .mem_size(core::mem::size_of::<Channel<ShmemMode, T, N>>())
            .try_into()
            .map_err(|_| QueError::InvalidSize)?;

        // Open shmem
        let shmem = Shmem::open_or_create(
            shmem_id,
            buffer_size,
            #[cfg(target_os = "linux")]
            page_size,
        )?;

        Consumer::join_multi(shmem.get_mut_ptr(), index, num_consumers)
    }

    /// Joins an existing channel backed by `buffer`.
    ///
    /// SAFETY:
    /// This must point to a buffer of proper size and alignment.
    pub unsafe fn join(
        buffer: *mut u8,
    ) -> Result<Consumer<ShmemMode, T, N>, QueError> {
        Self::join_multi(buffer, 0, 1)
    }

    /// Joins an existing channel backed by `buffer` as a consumer.
    ///
    /// `interval` is the number of consumers. This channel is not FIFO!
    /// To consume all produced values, you must consume all values
    /// generated by all consumers generated via `next_multi`.
    ///
    /// SAFETY:
    /// This must point to a buffer of proper size and alignment.
    pub unsafe fn join_multi(
        buffer: *mut u8,
        index: usize,
        consumers: usize,
    ) -> Result<Consumer<ShmemMode, T, N>, QueError> {
        Self::join_multi_(buffer, index, consumers)
    }
}

impl<M: ChannelMode<T>, T, const N: usize> Consumer<M, T, N> {
    pub const MODULO_MASK: usize = N - 1;

    pub(crate) unsafe fn join_multi_(
        buffer: *mut u8,
        index: usize,
        consumers: usize,
    ) -> Result<Consumer<M, T, N>, QueError> {
        assert!(
            N > 0 && N.is_power_of_two(),
            "Capacity must be a power of two"
        );
        assert!(buffer as usize % 128 == 0, "unaligned");
        assert!(
            consumers <= 64,
            "interval must be less than or equal to 64"
        );
        assert!(
            index < consumers,
            "index must be less than the total number of consumers"
        );

        let spsc: *mut Channel<M, T, N> = buffer.cast();

        // Check magic
        let magic = (*spsc).magic.load(Ordering::Acquire);
        let capacity = (*spsc).capacity.load(Ordering::Acquire);
        if magic == MAGIC {
            // Check capacity
            if capacity != N {
                return Err(QueError::IncorrectCapacity(capacity));
            }

            // Assume spsc is empty upon joining and set our cursor to the tail
            let head = (*spsc).tail.load(Ordering::Acquire);

            if M::BACKED_BY_ARCC {
                unsafe {
                    Arc::increment_strong_count(spsc);
                }
            }

            // Successful join if magic and capacity is correct
            Ok(Consumer {
                spsc: NonNull::new_unchecked(buffer.cast()),
                head: next_modulo(head, index, consumers),
                interval: consumers,
                consumer_index: index,
                last_producer_heartbeat: (*spsc)
                    .producer_heartbeat
                    .load(Ordering::Acquire),
            })
        } else if magic == 0 {
            // Technically could be corrupted but uninitialized
            // is most likely explanation
            Err(QueError::Uninitialized)
        } else {
            // Magic is not MAGIC and not zero
            println!("magic = {}; expected {}", magic, MAGIC);
            Err(QueError::CorruptionDetected)
        }
    }
    /// Attempts to read the next element. Returns `None` if the
    /// consuemr is caught up.
    pub fn pop(&mut self) -> Option<T> {
        loop {
            let initial_tail = unsafe {
                (*self.spsc.as_ptr())
                    .tail
                    .load(Ordering::Acquire)
            };

            // Check if there's anything to read
            let previously_read_or_uninitialized =
                initial_tail <= self.head;
            if previously_read_or_uninitialized {
                return None;
            }

            // Check for overrun
            let not_overrun = initial_tail
                <= (self
                    .head
                    .wrapping_add(N - burst_amount::<N>()));
            if !not_overrun {
                // Must reset to next integer that is consumer_index % interval
                self.head = next_modulo(
                    initial_tail.wrapping_sub(N - burst_amount::<N>()),
                    self.consumer_index,
                    self.interval,
                );
                continue;
            }

            // Optimistically read value and then check if valid
            let head_index = self.head & Self::MODULO_MASK;
            let value = unsafe {
                core::ptr::read(
                    (*self.spsc.as_ptr())
                        .buffer
                        .as_ptr()
                        .add(head_index),
                )
            };

            // Check if still not overrun
            let current_tail = unsafe {
                (*self.spsc.as_ptr())
                    .tail
                    .load(Ordering::Acquire)
            };
            let still_not_overrun = current_tail
                <= (self
                    .head
                    .wrapping_add(N - burst_amount::<N>()));

            // If overrun, update head and try again
            if !still_not_overrun {
                // Must reset to next integer that is consumer_index %
                // interval
                self.head = next_modulo(
                    current_tail.wrapping_sub(N - burst_amount::<N>()),
                    self.consumer_index,
                    self.interval,
                );
                continue;
            }

            self.head += self.interval;
            return Some(value);
        }
    }

    /// Increments the consumer heartbeat.
    ///
    /// Can be read by the producer to see that the consumer is still
    /// online if done periodically. Can also be used to ack individual
    /// messages or alert that we've joined.
    pub fn beat(&self) {
        unsafe {
            (*self.spsc.as_ptr())
                .consumer_heartbeat
                .fetch_add(1, Ordering::Release);
        }
    }

    /// Checks if the producer has incremented its heartbeat since last
    /// called. Can be used by the consumer to see if the producer is
    /// still online if done periodically. Can also be used to ack
    /// individual messages or alert that we've joined.
    pub fn producer_heartbeat(&mut self) -> bool {
        let heartbeat = unsafe {
            (*self.spsc.as_ptr())
                .producer_heartbeat
                .load(Ordering::Acquire)
        };

        if heartbeat != self.last_producer_heartbeat {
            self.last_producer_heartbeat = heartbeat;
            true
        } else {
            false
        }
    }

    /// Returns pointer to inner padding.
    ///
    /// User is responsible for safe usage.
    ///
    /// Can be used to store metadata (e.g. hash seed).
    ///
    /// Byte array is 128 byte aligned.
    pub fn get_padding_ptr(&self) -> NonNull<[u8; 112]> {
        unsafe {
            NonNull::new_unchecked(
                self.spsc.cast::<u8>().as_ptr().add(512),
            )
            .cast()
        }
    }
}

#[inline(always)]
fn next_modulo(
    head: usize,
    target_mod: usize,
    mod_value: usize,
) -> usize {
    let head_mod = head % mod_value;
    let add_value = (target_mod + mod_value - head_mod) % mod_value;
    head + add_value
}

impl<M: ChannelMode<T>, T, const N: usize> Drop for Consumer<M, T, N> {
    fn drop(&mut self) {
        // LocalMode is backed by arc
        if M::BACKED_BY_ARCC {
            unsafe { drop(Arc::from_raw(self.spsc.as_ptr())) }
        }
    }
}
